# .gitlab-ci.yml
#
# sccache


stages:
  - check
  - test
  - deploy

variables:
  GIT_STRATEGY:                    fetch
  GIT_DEPTH:                       100
  CARGO_INCREMENTAL:               0
  # this var is changed to "-:staging" when the CI image gets rebuilt
  # read more https://github.com/paritytech/scripts/pull/244
  CI_IMAGE:                        "paritytech/sccache-ci-ubuntu:production"

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

.docker-env:                       &docker-env
  image:                           "${CI_IMAGE}"
  before_script:
    - which gcc && gcc --version
    - which clang && clang --version
    - rustc +stable --version
    - rustc +nightly --version
    - sccache -s
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure
  interruptible:                   true
  tags:
    - linux-docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_REF_NAME == "master"
    - if: $CI_COMMIT_REF_NAME == "tags"
    - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs
    - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/              # i.e. v1.0, v2.1rc1

.collect-artifacts:                &collect-artifacts
  artifacts:
    name:                          "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when:                          on_success
    expire_in:                     7 days
    paths:
      - artifacts/

#### stage:                       check

dist-test:
  <<:                              *docker-env
  stage:                           check
  variables:
    A:                             b
    # all variables are passed to the services
  # ref https://docs.gitlab.com/ce/ci/docker/using_docker_images.html#available-settings-for-services
  services:
    - name:                        $CI_IMAGE # to change when we'll have our own release
      alias:                       scheduler
      # https://github.com/paritytech/sccache/pull/4/commits/678f77bb94d72ec1737f5ae80b7413000ff86cdb
      command:                     ["sccache", "start-server"] # syntax: CMD ["executable","param1","param2"]
    - name:                        $CI_IMAGE # to change when we'll have our own release
      alias:                       server
      command:                     ["sccache", "start-server"]
  script:
    - sccache -s
    # - cargo test --features=dist-tests,dist-client,dist-server
