on:
  # Run on every push on every branch
  push:
    branches-ignore:
      # Ignore branches automatically created by github-rebase
      - rebase-pull-request**
      - cherry-pick-rebase-pull-request**
  # Run when pull requests get labeled
  pull_request:
    types:                  [labeled]

jobs:
  auto-rebase:
    name:                   AutoRebase
    runs-on:                ubuntu-latest
    steps:
      - name:               Auto Rebase
        uses:               Label305/AutoRebase@v0.1
        with:
          github_token:     ${{ secrets.TOKEN_GEN_APP_SECRET }}
